name: pgd-demo-py311
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Python 3.11 (recommended)
  - pytorch=2.1.0  # Latest stable PyTorch
  - torchvision=0.16.0  # Compatible torchvision
  - matplotlib=3.8.0  # Latest matplotlib
  - numpy=1.25.2  # Latest numpy compatible with Python 3.11
  - seaborn=0.13.0  # Statistical data visualization
  - jupyter=1.0.0
  - ipykernel=6.25.0  # Latest ipykernel
  - tqdm=4.66.0  # Latest tqdm
  - pillow=11.3.0  # Latest pillow
  - scikit-learn=1.3.0  # Latest scikit-learn
  - pip
  - scikit-image=0.25.2  # Latest scikit-image
  - uv
  - pip:
    - ipywidgets==8.1.0  # Latest ipywidgets